# 1 start docker kernel with python 
FROM python:3.11.6-slim-bullseye
# show pyhton logs
ENV PYTHONUNBUFFERED = 1
#update kernel + install 
RUN apt-get update && apt-get -y install gcc libpq-dev
#folder for my project
WORKDIR /app
#copy requirements 
COPY requirements.txt /app/requirements.txt
# install requirements
RUN pip install -r /app/requirements.txt
#copy all project files
COPY . /app/